global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'crm-spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9039'] 

  - job_name: 'chat-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9100']